# Generated by Django 4.2.29 on 2026-04-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('EXAM', 'ข้อสอบเก่า'), ('SUM', 'สรุปบทเรียน')], max_length=10),
        ),
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
