# Generated by Django 4.2.29 on 2026-04-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_alter_document_category_alter_document_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('SUM', 'สรุปบทเรียน'), ('EXAM', 'ข้อสอบเก่า')], max_length=4),
        ),
        migrations.AlterField(
            model_name='document',
            name='subject_code',
            field=models.CharField(max_length=10),
        ),
    ]
