# Generated by Django 4.2.29 on 2026-04-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0003_document_file_alter_document_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='subject_category',
            field=models.CharField(choices=[('MATH', 'คณิตศาสตร์'), ('SCI', 'วิทยาศาสตร์'), ('LANG', 'ภาษา'), ('COM', 'คอมพิวเตอร์'), ('SOC', 'สังคมศึกษา')], default='MATH', max_length=10),
        ),
    ]
